### ISSUE TITLE
Create ADRs

### ISSUE THREAD

**Issue by PierreBeur** [cse110-fa22-group24/cse110-fa22-group24#12]
[Canvas Assignment](https://canvas.ucsd.edu/courses/39754/assignments/526059)

We will eventually capture these as an [ADR in markdown](https://adr.github.io/madr/).
(`/specs/adrs` will contain an individual document per major decision.  There will be some initial ones that have to do with general project plan and approach, but more may be added as the project goes on.  The main point of this capture is to explain why choices are made.  As brainstorming may have your team settle on choices quickly capturing them in a document may be better than just mental consensus) 

- [x] #30 - due in repo by 11/13
- [ ] Checkpoint 2 - due in repo by 11/22
- [ ] Final checkpoint will be on your project review (final exam date)
  
Individual items:
- [x] #68 
- [x] #71 
- [x] #69 
- [x] #72 
- [x] #70

**Comment by HaykTheKhulyan** [comment]
I tried linking the pull request I made, but it seems like that would close the issue, even though we still have two checkpoints after this. We might want to create three separate issues for each checkpoint.

**Comment by PierreBeur** [comment]
Just created a new issue for the checkpoint: #30
