### ISSUE TITLE
Add User Centered Thinking Documents

### ISSUE THREAD

**Issue by PierreBeur** [cse110-fa22-group24/cse110-fa22-group24#21]
We will produce [personas](http://opendesignkit.org/methods/personas/), [user stories](https://en.wikipedia.org/wiki/User_story), and potentially [use cases](https://en.wikipedia.org/wiki/Use_case).
(`/specs/users` will contain this but user stories chosen will also be represented as issues to work on)

**Comment by isabelle-kr** [comment]
Uploaded
