### ISSUE TITLE
Add Brainstorming Documents

### ISSUE THREAD

**Issue by PierreBeur** [cse110-fa22-group24/cse110-fa22-group24#25]
`/specs/brainstorm/` will contain the distilled documents and diagrams you produced.  If you used Miro or another tool export the contents as an image, PDF, or markdown file to capture your appropriate assets.

- [x] [Miro](https://miro.com/app/board/uXjVPJ8rcC4=/)
- [x] [Figma](https://www.figma.com/file/MJNu9BIF2qha5lbEGSJRCw/CSE-110)

**Comment by Eric890916** [comment]
uploaded

**Comment by PierreBeur** [comment]
`/specs/brainstorm/` should probably have a screenshot of the [Miro board](https://miro.com/app/board/uXjVPJ8rcC4=/).

**Comment by Eric890916** [comment]
added
