### ISSUE TITLE
Create Custom Scroll Bar

### ISSUE THREAD

**Issue by JessalynWang** [cse110-fa22-group24/cse110-fa22-group24#47]
![image](https://user-images.githubusercontent.com/42593027/202351604-7942e1a0-6c76-4fa6-8858-d1398f69ce3c.png)

[https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)

make sure this works with different browsers (if on windows, check with someone in mac)

**Comment by PierreBeur** [comment]
Completely unsupported on Firefox on all devices and operating systems.

**Comment by PierreBeur** [comment]
Completely unsupported on Firefox on all devices and operating systems.
